services:
  public_api:
    build: .
    env_file:
      - .env
    volumes:
      - .:/car_api
    ports:
      - 8000:8000
    image: app:car_api
    container_name: car_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - postgres
 
  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db 